wip: Disable Download button until test issue is figured out
Error:

● Test suite failed to run

  /Users/kgilpin/source/appland/appmap-js/node_modules/dom-to-svg/lib/index.js:1
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as postcss from 'postcss';
                                                                                          ^^^^^^

  SyntaxError: Cannot use import statement outside a module

    5 | <script>
    6 | import assert from 'assert';
  >  7 | import { elementToSVG, inlineResources } from 'dom-to-svg';
      | ^
    8 |
    9 | export default {
    10 |   name: 'v-download-sequence-diagram',

    at ScriptTransformer._transformAndBuildScript (../../node_modules/@vue/cli-plugin-unit-jest/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
    at src/components/sequence/DownloadSequenceDiagram.vue:7:1
    at Object.<anonymous> (src/components/sequence/DownloadSequenceDiagram.vue:46:3)